### ISSUE TITLE
spotipy fails a lot

### ISSUE THREAD

**Issue by puttin** [zhang435/Xiami_To_Spotify#1]
how about store last successful Xiami list locally and run add to Spotify playlist directly?

I have nearly 2k songs in Xiami, and even run program on my VPS at Japan fails a lot.

**Comment by zhang435** [comment]
So the problem is when you fetch songs from XIAMI the poor network will break the code?
The problem with "store last successful Xiami list" is if you only get first 20 songs first time, at second time, those 20 songs will added into Spotify playlist again

**Comment by puttin** [comment]
I found out the main problem is not the crawler of Xiami. It's the search Spotify for better result part.
The crawler is pretty good without the Spotify search.

---

Then I modify a little of your program to export Xiami first, then search and add to playlist.
Also add manually-change which song to begin in Xiami list to workaround other Spotify problem.
After all of this, I use https://github.com/JMPerez/spotify-dedup/ to remove duplicated songs.
Your scripts is the key of all. Thank you.

---

I think the main problem is that Spotify has a [rate limit](https://developer.spotify.com/web-api/user-guide/#rate-limiting). But `spotipy` may not respect that.

**Comment by zhang435** [comment]
I am glad this project helps, if you can/want, please make a pull request, I will merge the part you changed, so it may help other users. I didn't have your problem when I use it. I have 1200 songs in Xiami as well, Even I can not recur your problem. I think it good your have your part so that other user can take benefit on this.
